.PHONY: clean All

All:
	@echo "----------Building project:[ PortasLogicas - Debug ]----------"
	@cd "PortasLogicas" && $(MAKE) -f  "PortasLogicas.mk"
clean:
	@echo "----------Cleaning project:[ PortasLogicas - Debug ]----------"
	@cd "PortasLogicas" && $(MAKE) -f  "PortasLogicas.mk" clean
