.PHONY: clean All

All:
	@echo "----------Building project:[ Uinio - Debug ]----------"
	@$(MAKE) -f  "Uinio.mk"
clean:
	@echo "----------Cleaning project:[ Uinio - Debug ]----------"
	@$(MAKE) -f  "Uinio.mk" clean
